;; Problem 44
;; Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

;; 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

;; It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

;; Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


(ns project-euler-clj.problem-044
  (:require [project-euler-clj.common :as common])
  (:require [clojure.set :as sets])
  (:require [clojure.math.combinatorics :as combo]))

(defn lazy-petangonal-nums
  ([] (lazy-petangonal-nums 1 4))
  ([n diff] (cons n (lazy-seq (lazy-petangonal-nums (+ n diff) (+ diff 3))))))

(take 20 (lazy-petangonal-nums))

(defn solve
  []
  (loop [pen-seq (lazy-petangonal-nums)
       acc []
       candidates []]
  (let [term (first pen-seq)
        new-cands (concat candidates
                          (map (fn [n] {:pair [n term]
                                        :diff (- term n)
                                        :sum (+ n term)})
                               (filter (fn [n] (some #{(- term n)} acc))
                                       acc)))
        new-sols (filter #(= term
                             (% :sum))
                         new-cands)]
    (if (or (< 0 (count new-sols)))
      new-sols
      (recur (rest pen-seq)
             (conj acc term)
             new-cands)))))
;; ({:pair [1560090 7042750], :diff 5482660, :sum 8602840})
