;; The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

;; Let us list the factors of the first seven triangle numbers:

;;  1: 1
;;  3: 1,3
;;  6: 1,2,3,6
;; 10: 1,2,5,10
;; 15: 1,3,5,15
;; 21: 1,3,7,21
;; 28: 1,2,4,7,14,28
;; We can see that 28 is the first triangle number to have over five divisors.

;; What is the value of the first triangle number to have over five hundred divisors?
(ns project-euler-clj.problem-12)
(require '[project-euler-clj.common :as common])

(defn factor-num
  [target]
  (bigint (reduce * (map #(inc (:exp %)) (common/prime-factor target)))))

(def condition (fn [n] (<= 500 (factor-num n))))
(def num-seq-func (fn [n] (/ (* n (inc n)) 2)))
(> (num-seq-func 14) 100)

(loop [i 1]
  (let [n (num-seq-func i)]
    (if (condition n)
      {:index i :value n :factors (common/prime-factor n)}
      (recur (inc i)))))
;; Answer
;; {:index 12375,
;;  :value 76576500,
;;  :factors
;;  [{:factor 2, :exp 2}
;;   {:factor 3, :exp 2}
;;   {:factor 5, :exp 3}
;;   {:factor 7, :exp 1}
;;   {:factor 11, :exp 1}
;;   {:factor 13, :exp 1}
;;   {:factor 17, :exp 1}]}
